@baseUrl = {{ENV_BASE_URL}}

###

# @name staffLogin
POST {{baseUrl}}/auth/staff/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin1234"
}

###

# @name refresh
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{staffLogin.response.body.$.refreshToken}}"
}

###

# @name me
GET {{baseUrl}}/auth/me
Authorization: Bearer {{staffLogin.response.body.$.accessToken}}

###

# @name logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{staffLogin.response.body.$.accessToken}}

###

# @name adminPing
GET {{baseUrl}}/auth/admin/ping
Authorization: Bearer {{staffLogin.response.body.$.accessToken}}

###

# @name customerRegister
POST {{baseUrl}}/auth/customer/register
Content-Type: application/json

{
  "email": "buyer@example.com",
  "password": "buyer1234",
  "firstName": "Buy",
  "lastName": "Er"
}

###

# @name customerLogin
POST {{baseUrl}}/auth/customer/login
Content-Type: application/json

{
  "email": "buyer@example.com",
  "password": "buyer1234"
}

###

# @name customerMe
GET {{baseUrl}}/auth/customer/me
Authorization: Bearer {{customerLogin.response.body.$.accessToken}}
