@baseUrl = {{ENV_BASE_URL}}

###

# @name login
POST {{baseUrl}}/auth/customer/login
Content-Type: application/json

{
  "email": "customer@example.com",
  "password": "customer1234"
}

###
@accessToken = {{login.response.body.$.accessToken}}

###

# @name getMyConsent
GET {{baseUrl}}/auth/customer/me/consent
Authorization: Bearer {{accessToken}}

###

# @name setMyConsentMarketingOn
PUT {{baseUrl}}/auth/customer/me/consent
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "marketingEmail": true
}

###

# @name setMyConsentMarketingOff
PUT {{baseUrl}}/auth/customer/me/consent
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "marketingEmail": false
}

###

# @name setRetentionPolicy
PUT {{baseUrl}}/auth/customer/me/consent
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "dataRetentionPolicy": "default-7-years"
}
