export const RESERVATION_SWEEP_BATCH_SIZE = Symbol('RESERVATION_SWEEP_BATCH_SIZE');
export const RESERVATION_SWEEP_TRANSACTION_SIZE = Symbol('RESERVATION_SWEEP_TRANSACTION_SIZE');
export const RESERVATION_SWEEP_INTERVAL_SECONDS = Symbol('RESERVATION_SWEEP_INTERVAL_SECONDS');
