export enum PermissionCodeEnum {
  CATALOG_READ = 'catalog:read',
  CATALOG_WRITE = 'catalog:write',
  CATALOG_PUBLISH = 'catalog:publish',
  INVENTORY_READ = 'inventory:read',
  INVENTORY_ADJUST = 'inventory:adjust',
  INVENTORY_TRANSFER = 'inventory:transfer',
  INVENTORY_RECEIVE_RETURN = 'inventory:receive-return',
  ORDER_READ = 'order:read',
  ORDER_CAPTURE = 'order:capture',
  ORDER_FULFILL = 'order:fulfill',
  ORDER_CANCEL = 'order:cancel',
  ORDER_REFUND = 'order:refund',
  ORDER_RETURN_AUTHORIZE = 'order:return-authorize',
  NOTIFICATIONS_READ = 'notifications:read',
  NOTIFICATIONS_WRITE = 'notifications:write',
  IAM_STAFF_CREATE = 'iam:staff-create',
  IAM_ASSIGN = 'iam:assign',
  IAM_ROLE_EDIT = 'iam:role-edit',
  AUDIT_READ = 'audit:read',
  PRICING_WRITE = 'pricing:write',
  CUSTOMER_READ_CONSENT = 'customer:read-consent',
  CUSTOMER_ERASE = 'customer:erase',
}
