export enum MicroserviceClientTokenEnum {
  INVENTORY_MICROSERVICE = 'INVENTORY_MICROSERVICE',
  RETAIL_MICROSERVICE = 'RETAIL_MICROSERVICE',
  NOTIFICATION_MICROSERVICE = 'NOTIFICATION_MICROSERVICE',
  CATALOG_MICROSERVICE = 'CATALOG_MICROSERVICE',

  EVENT_STORE_MICROSERVICE = 'EVENT_STORE_MICROSERVICE',

  RIS_EVENTS_PUBLISHER = 'RIS_EVENTS_PUBLISHER',
}
