// Wire-format routing keys. Kept in lock-step with `ROUTING_KEYS` in
// libs/messaging — this enum is the source of truth, `ROUTING_KEYS` is the
// idiomatic constants surface for new callers.
export enum MicroserviceMessagePatternEnum {
  INVENTORY_ORDER_CONFIRM = 'inventory.order.confirm',
  INVENTORY_STOCK_LOW = 'inventory.stock.low',
  RETAIL_ORDER_CREATE = 'retail.order.create',
  RETAIL_ORDER_CONFIRM = 'retail.order.confirm',
  RETAIL_ORDER_GET = 'retail.order.get',
  RETAIL_ORDER_CREATED = 'retail.order.created',
  RETAIL_ORDER_CONFIRMED = 'retail.order.confirmed',
  RETAIL_ORDER_CANCELLED = 'retail.order.cancelled',
  CATALOG_PRODUCT_REGISTER = 'catalog.product.register',
  CATALOG_PRODUCT_PUBLISH = 'catalog.product.publish',
  CATALOG_PRODUCT_ARCHIVE = 'catalog.product.archive',
  CATALOG_VARIANT_CREATE = 'catalog.variant.create',
  CATALOG_VARIANT_CREATED = 'catalog.variant.created',
  CATALOG_PRODUCT_PUBLISHED = 'catalog.product.published',
  CATALOG_PRODUCT_ARCHIVED = 'catalog.product.archived',
  CATALOG_PRODUCT_LIST = 'catalog.product.list',
  CATALOG_PRODUCT_GET = 'catalog.product.get',
  CATALOG_VARIANT_GET = 'catalog.variant.get',
  CATALOG_PRICE_SET = 'catalog.price.set',
  CATALOG_PRICE_LIST = 'catalog.price.list',
  CATALOG_PRICE_SELECT = 'catalog.price.select',
  CATALOG_PRICE_CHANGED = 'catalog.price.changed',
  CATALOG_PRICE_SCHEDULED = 'catalog.price.scheduled',
  CATALOG_TAX_CATEGORY_CREATE = 'catalog.tax-category.create',
  CATALOG_TAX_CATEGORY_LIST = 'catalog.tax-category.list',
  CATALOG_VARIANT_SET_TAX_CATEGORY = 'catalog.variant.set-tax-category',
  NOTIFICATION_HEALTH_PING = 'notification.health.ping',
}
