export enum MicroserviceClientTokenEnum {
  INVENTORY_MICROSERVICE = 'INVENTORY_MICROSERVICE',
  RETAIL_MICROSERVICE = 'RETAIL_MICROSERVICE',
  NOTIFICATION_MICROSERVICE = 'NOTIFICATION_MICROSERVICE',
  CATALOG_MICROSERVICE = 'CATALOG_MICROSERVICE',
}
