export enum NotificationErrorCodeEnum {
  TEMPLATE_BODY_REQUIRED = 'NOTIFICATION_TEMPLATE_BODY_REQUIRED',
  TEMPLATE_SUBJECT_REQUIRED = 'NOTIFICATION_TEMPLATE_SUBJECT_REQUIRED',
  TEMPLATE_EVENT_TYPE_REQUIRED = 'NOTIFICATION_TEMPLATE_EVENT_TYPE_REQUIRED',
  TEMPLATE_LOCALE_REQUIRED = 'NOTIFICATION_TEMPLATE_LOCALE_REQUIRED',
  TEMPLATE_VERSION_INVALID = 'NOTIFICATION_TEMPLATE_VERSION_INVALID',
  DELIVERY_RECIPIENT_REQUIRED = 'NOTIFICATION_DELIVERY_RECIPIENT_REQUIRED',
  DELIVERY_INVALID_STATUS_TRANSITION = 'NOTIFICATION_DELIVERY_INVALID_STATUS_TRANSITION',

  TEMPLATE_NOT_FOUND = 'NOTIFICATION_TEMPLATE_NOT_FOUND',
  TEMPLATE_DUPLICATE_VERSION = 'NOTIFICATION_TEMPLATE_DUPLICATE_VERSION',
  DELIVERY_NOT_FOUND = 'NOTIFICATION_DELIVERY_NOT_FOUND',
}
