import { DomainException } from '@retail-inventory-system/common';

export enum InventoryErrorCodeEnum {
  STOCK_RECEIVE_QUANTITY_INVALID = 'INVENTORY_STOCK_RECEIVE_QUANTITY_INVALID',
  STOCK_ADJUSTMENT_DELTA_INVALID = 'INVENTORY_STOCK_ADJUSTMENT_DELTA_INVALID',
  STOCK_ADJUSTMENT_REASON_REQUIRED = 'INVENTORY_STOCK_ADJUSTMENT_REASON_REQUIRED',

  TRANSFER_QUANTITY_INVALID = 'INVENTORY_TRANSFER_QUANTITY_INVALID',
  TRANSFER_SAME_LOCATION = 'INVENTORY_TRANSFER_SAME_LOCATION',

  STOCK_LOCATION_NOT_FOUND = 'INVENTORY_STOCK_LOCATION_NOT_FOUND',
  STOCK_LOCATION_INACTIVE = 'INVENTORY_STOCK_LOCATION_INACTIVE',
  STOCK_RESULT_NEGATIVE = 'INVENTORY_STOCK_RESULT_NEGATIVE',

  STOCK_WRITE_CONFLICT = 'INVENTORY_STOCK_WRITE_CONFLICT',

  RESERVATION_QUANTITY_INVALID = 'INVENTORY_RESERVATION_QUANTITY_INVALID',

  RESERVATION_INVALID_STATE = 'INVENTORY_RESERVATION_INVALID_STATE',

  RESERVATION_EXPIRED = 'INVENTORY_RESERVATION_EXPIRED',

  OUT_OF_STOCK = 'INVENTORY_OUT_OF_STOCK',

  RESERVATION_NOT_FOUND = 'INVENTORY_RESERVATION_NOT_FOUND',

  RESERVATION_SELECTOR_INVALID = 'INVENTORY_RESERVATION_SELECTOR_INVALID',
}

export class InventoryDomainException extends DomainException {
  public readonly code: InventoryErrorCodeEnum;
  public readonly details?: Readonly<Record<string, unknown>>;

  constructor(
    code: InventoryErrorCodeEnum,
    message: string,
    details?: Readonly<Record<string, unknown>>,
  ) {
    super(message);
    this.code = code;
    this.details = details;
  }
}
