import { MicroserviceMessagePatternEnum } from '@retail-inventory-system/contracts';

import { ROUTING_KEYS } from '../routing-keys.constants';

// Wire-format alignment: the `ROUTING_KEYS` constants in `libs/messaging` and
// the `MicroserviceMessagePatternEnum` values in `libs/contracts` must agree
// — both libraries are imported by gateway and microservices and a drift
// would silently route messages to the wrong queue.
describe('ROUTING_KEYS', () => {
  it('matches MicroserviceMessagePatternEnum values', () => {
    expect(ROUTING_KEYS.INVENTORY_ORDER_CONFIRM).toBe(
      MicroserviceMessagePatternEnum.INVENTORY_ORDER_CONFIRM,
    );
    expect(ROUTING_KEYS.INVENTORY_STOCK_LOW).toBe(
      MicroserviceMessagePatternEnum.INVENTORY_STOCK_LOW,
    );
    expect(ROUTING_KEYS.INVENTORY_STOCK_RECEIVED).toBe(
      MicroserviceMessagePatternEnum.INVENTORY_STOCK_RECEIVED,
    );
    expect(ROUTING_KEYS.INVENTORY_STOCK_ADJUSTED).toBe(
      MicroserviceMessagePatternEnum.INVENTORY_STOCK_ADJUSTED,
    );
    expect(ROUTING_KEYS.INVENTORY_STOCK_LEVEL_GET).toBe(
      MicroserviceMessagePatternEnum.INVENTORY_STOCK_LEVEL_GET,
    );
    expect(ROUTING_KEYS.INVENTORY_STOCK_LEVEL_RECEIVE).toBe(
      MicroserviceMessagePatternEnum.INVENTORY_STOCK_LEVEL_RECEIVE,
    );
    expect(ROUTING_KEYS.INVENTORY_STOCK_LEVEL_ADJUST).toBe(
      MicroserviceMessagePatternEnum.INVENTORY_STOCK_LEVEL_ADJUST,
    );
    expect(ROUTING_KEYS.INVENTORY_STOCK_LEVEL_INITIALIZED).toBe(
      MicroserviceMessagePatternEnum.INVENTORY_STOCK_LEVEL_INITIALIZED,
    );
    expect(ROUTING_KEYS.INVENTORY_LOCATION_LIST).toBe(
      MicroserviceMessagePatternEnum.INVENTORY_LOCATION_LIST,
    );
    expect(ROUTING_KEYS.CATALOG_PRODUCT_REGISTER).toBe(
      MicroserviceMessagePatternEnum.CATALOG_PRODUCT_REGISTER,
    );
    expect(ROUTING_KEYS.CATALOG_PRODUCT_PUBLISH).toBe(
      MicroserviceMessagePatternEnum.CATALOG_PRODUCT_PUBLISH,
    );
    expect(ROUTING_KEYS.CATALOG_PRODUCT_ARCHIVE).toBe(
      MicroserviceMessagePatternEnum.CATALOG_PRODUCT_ARCHIVE,
    );
    expect(ROUTING_KEYS.CATALOG_VARIANT_CREATE).toBe(
      MicroserviceMessagePatternEnum.CATALOG_VARIANT_CREATE,
    );
    expect(ROUTING_KEYS.CATALOG_VARIANT_CREATED).toBe(
      MicroserviceMessagePatternEnum.CATALOG_VARIANT_CREATED,
    );
    expect(ROUTING_KEYS.CATALOG_PRODUCT_PUBLISHED).toBe(
      MicroserviceMessagePatternEnum.CATALOG_PRODUCT_PUBLISHED,
    );
    expect(ROUTING_KEYS.CATALOG_PRODUCT_ARCHIVED).toBe(
      MicroserviceMessagePatternEnum.CATALOG_PRODUCT_ARCHIVED,
    );
    expect(ROUTING_KEYS.CATALOG_PRODUCT_LIST).toBe(
      MicroserviceMessagePatternEnum.CATALOG_PRODUCT_LIST,
    );
    expect(ROUTING_KEYS.CATALOG_PRODUCT_GET).toBe(
      MicroserviceMessagePatternEnum.CATALOG_PRODUCT_GET,
    );
    expect(ROUTING_KEYS.CATALOG_VARIANT_GET).toBe(
      MicroserviceMessagePatternEnum.CATALOG_VARIANT_GET,
    );
    expect(ROUTING_KEYS.CATALOG_PRICE_SET).toBe(MicroserviceMessagePatternEnum.CATALOG_PRICE_SET);
    expect(ROUTING_KEYS.CATALOG_PRICE_LIST).toBe(MicroserviceMessagePatternEnum.CATALOG_PRICE_LIST);
    expect(ROUTING_KEYS.CATALOG_PRICE_SELECT).toBe(
      MicroserviceMessagePatternEnum.CATALOG_PRICE_SELECT,
    );
    expect(ROUTING_KEYS.CATALOG_PRICE_CHANGED).toBe(
      MicroserviceMessagePatternEnum.CATALOG_PRICE_CHANGED,
    );
    expect(ROUTING_KEYS.CATALOG_PRICE_SCHEDULED).toBe(
      MicroserviceMessagePatternEnum.CATALOG_PRICE_SCHEDULED,
    );
    expect(ROUTING_KEYS.CATALOG_TAX_CATEGORY_CREATE).toBe(
      MicroserviceMessagePatternEnum.CATALOG_TAX_CATEGORY_CREATE,
    );
    expect(ROUTING_KEYS.CATALOG_TAX_CATEGORY_LIST).toBe(
      MicroserviceMessagePatternEnum.CATALOG_TAX_CATEGORY_LIST,
    );
    expect(ROUTING_KEYS.CATALOG_VARIANT_SET_TAX_CATEGORY).toBe(
      MicroserviceMessagePatternEnum.CATALOG_VARIANT_SET_TAX_CATEGORY,
    );
    expect(ROUTING_KEYS.CATALOG_CATEGORY_CREATE).toBe(
      MicroserviceMessagePatternEnum.CATALOG_CATEGORY_CREATE,
    );
    expect(ROUTING_KEYS.CATALOG_CATEGORY_REPARENT).toBe(
      MicroserviceMessagePatternEnum.CATALOG_CATEGORY_REPARENT,
    );
    expect(ROUTING_KEYS.RETAIL_CART_CREATE).toBe(MicroserviceMessagePatternEnum.RETAIL_CART_CREATE);
    expect(ROUTING_KEYS.RETAIL_CART_GET).toBe(MicroserviceMessagePatternEnum.RETAIL_CART_GET);
    expect(ROUTING_KEYS.RETAIL_CART_ADD_LINE).toBe(
      MicroserviceMessagePatternEnum.RETAIL_CART_ADD_LINE,
    );
    expect(ROUTING_KEYS.RETAIL_CART_CHANGE_LINE_QUANTITY).toBe(
      MicroserviceMessagePatternEnum.RETAIL_CART_CHANGE_LINE_QUANTITY,
    );
    expect(ROUTING_KEYS.RETAIL_CART_REMOVE_LINE).toBe(
      MicroserviceMessagePatternEnum.RETAIL_CART_REMOVE_LINE,
    );
    expect(ROUTING_KEYS.RETAIL_CART_CLAIM).toBe(MicroserviceMessagePatternEnum.RETAIL_CART_CLAIM);
    expect(ROUTING_KEYS.RETAIL_CART_PLACE).toBe(MicroserviceMessagePatternEnum.RETAIL_CART_PLACE);
    expect(ROUTING_KEYS.RETAIL_ORDER_GET).toBe(MicroserviceMessagePatternEnum.RETAIL_ORDER_GET);
    expect(ROUTING_KEYS.RETAIL_ORDER_LIST).toBe(MicroserviceMessagePatternEnum.RETAIL_ORDER_LIST);
    expect(ROUTING_KEYS.RETAIL_PAYMENT_CAPTURE).toBe(
      MicroserviceMessagePatternEnum.RETAIL_PAYMENT_CAPTURE,
    );
    expect(ROUTING_KEYS.RETAIL_PAYMENT_CAPTURED).toBe(
      MicroserviceMessagePatternEnum.RETAIL_PAYMENT_CAPTURED,
    );
    expect(ROUTING_KEYS.RETAIL_ORDER_PLACED).toBe(
      MicroserviceMessagePatternEnum.RETAIL_ORDER_PLACED,
    );
    expect(ROUTING_KEYS.RETAIL_PAYMENT_AUTHORIZED).toBe(
      MicroserviceMessagePatternEnum.RETAIL_PAYMENT_AUTHORIZED,
    );
    expect(ROUTING_KEYS.RETAIL_CART_CREATED).toBe(
      MicroserviceMessagePatternEnum.RETAIL_CART_CREATED,
    );
    expect(ROUTING_KEYS.RETAIL_CART_LINE_ADDED).toBe(
      MicroserviceMessagePatternEnum.RETAIL_CART_LINE_ADDED,
    );
    expect(ROUTING_KEYS.RETAIL_CART_LINE_REMOVED).toBe(
      MicroserviceMessagePatternEnum.RETAIL_CART_LINE_REMOVED,
    );
    expect(ROUTING_KEYS.RETAIL_CART_LINE_QUANTITY_CHANGED).toBe(
      MicroserviceMessagePatternEnum.RETAIL_CART_LINE_QUANTITY_CHANGED,
    );
    expect(ROUTING_KEYS.NOTIFICATION_HEALTH_PING).toBe(
      MicroserviceMessagePatternEnum.NOTIFICATION_HEALTH_PING,
    );
  });

  it('uses dotted naming convention', () => {
    for (const value of Object.values(ROUTING_KEYS)) {
      expect(value).toMatch(/^[a-z]+(\.[a-z-]+)+$/);
    }
  });
});
