import { DomainException } from '@retail-inventory-system/common';

export enum PricingErrorCodeEnum {
  PRICE_AMOUNT_INVALID = 'PRICING_PRICE_AMOUNT_INVALID',
  PRICE_CURRENCY_INVALID = 'PRICING_PRICE_CURRENCY_INVALID',
  PRICE_INTERVAL_INVALID = 'PRICING_PRICE_INTERVAL_INVALID',
  PRICE_VALID_FROM_IN_PAST = 'PRICING_PRICE_VALID_FROM_IN_PAST',
  PRICE_PRIORITY_INVALID = 'PRICING_PRICE_PRIORITY_INVALID',
  PRICE_SCHEDULE_CONFLICT = 'PRICING_PRICE_SCHEDULE_CONFLICT',
  TAX_CATEGORY_CODE_INVALID = 'PRICING_TAX_CATEGORY_CODE_INVALID',
  TAX_CATEGORY_NAME_REQUIRED = 'PRICING_TAX_CATEGORY_NAME_REQUIRED',
  TAX_CATEGORY_CODE_TAKEN = 'PRICING_TAX_CATEGORY_CODE_TAKEN',
  TAX_CATEGORY_NOT_FOUND = 'PRICING_TAX_CATEGORY_NOT_FOUND',
  VARIANT_NOT_FOUND = 'PRICING_VARIANT_NOT_FOUND',
}

export class PricingDomainException extends DomainException {
  public readonly code: PricingErrorCodeEnum;

  constructor(code: PricingErrorCodeEnum, message: string) {
    super(message);
    this.code = code;
  }
}
