export enum MicroserviceClientNameEnum {
  INVENTORY_MICROSERVICE = 'INVENTORY_MICROSERVICE',
  RETAIL_MICROSERVICE = 'RETAIL_MICROSERVICE',
  NOTIFICATION_MICROSERVICE = 'NOTIFICATION_MICROSERVICE',
}
