INSERT IGNORE INTO notification_template (event_type, channel, locale, subject, body, version, active)
VALUES
  ('retail.order.placed', 'email', 'en-US',
   'Order #{{orderNumber}} confirmed',
   'Thank you! Order #{{orderNumber}} is confirmed: {{lineCount}} item(s) totaling {{grandTotalMinor}} {{currency}}.',
   1, 1),
  ('retail.fulfillment.shipped', 'email', 'en-US',
   'Order #{{orderId}} has shipped',
   'Your order #{{orderId}} has shipped via {{carrier}}. Track it with {{trackingNumber}}.',
   1, 1),
  ('retail.fulfillment.delivered', 'email', 'en-US',
   'Your order arrived',
   'Good news — your order #{{orderId}} has been delivered.',
   1, 1),
  ('retail.order.cancelled', 'email', 'en-US',
   'Order #{{orderId}} cancelled',
   'Your order #{{orderId}} has been cancelled. Reason: {{reason}}.',
   1, 1),
  ('retail.return.requested', 'email', 'en-US',
   'Return {{rmaNumber}} received',
   'We have received your return request {{rmaNumber}} for {{lineCount}} item(s).',
   1, 1),
  ('retail.return.authorized', 'email', 'en-US',
   'Return {{rmaNumber}} authorized',
   'Your return {{rmaNumber}} has been authorized. Please ship the item(s) back to us.',
   1, 1),
  ('retail.return.received', 'email', 'en-US',
   'Return {{rmaNumber}} received at warehouse',
   'We have received the item(s) for return {{rmaNumber}} at our warehouse.',
   1, 1),
  ('retail.return.inspected', 'email', 'en-US',
   'Return {{rmaNumber}} inspected',
   'Return {{rmaNumber}} has been inspected. {{restockedLineCount}} item(s) returned to stock.',
   1, 1),
  ('retail.refund.issued', 'email', 'en-US',
   'Refund issued',
   'A refund of {{amountMinor}} {{currency}} for order #{{orderId}} has been issued.',
   1, 1),
  ('inventory.stock.low', 'email', 'en-US',
   'Low stock alert',
   'Low stock for variant {{variantId}} at {{stockLocationId}}: {{quantity}} on hand (threshold {{threshold}}).',
   1, 1),
  ('marketing.email.promo', 'email', 'en-US',
   'A special offer just for you, {{customerName}}',
   'Hi {{customerName}}! Enjoy our latest promotion. Use code {{promoCode}} at checkout for a limited-time discount.',
   1, 1);
