import { DomainException } from '@retail-inventory-system/common';

export enum OrderErrorCodeEnum {
  ORDER_CURRENCY_INVALID = 'ORDER_CURRENCY_INVALID',
  ORDER_NO_LINES = 'ORDER_NO_LINES',
  ORDER_MONEY_INVALID = 'ORDER_MONEY_INVALID',
  ORDER_TOTAL_MISMATCH = 'ORDER_TOTAL_MISMATCH',
  ORDER_VERSION_INVALID = 'ORDER_VERSION_INVALID',
  ORDER_VERSION_MISMATCH = 'VERSION_MISMATCH',
  ORDER_INVALID_PAYMENT_TRANSITION = 'ORDER_INVALID_PAYMENT_TRANSITION',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_ACCESS_FORBIDDEN = 'ORDER_ACCESS_FORBIDDEN',

  ORDER_CART_NOT_FOUND = 'ORDER_CART_NOT_FOUND',
  ORDER_CART_ACCESS_FORBIDDEN = 'ORDER_CART_ACCESS_FORBIDDEN',
  ORDER_CART_NOT_PLACEABLE = 'ORDER_CART_NOT_PLACEABLE',
  ORDER_CART_EMPTY = 'ORDER_CART_EMPTY',
  ORDER_LINE_NO_PRICE = 'ORDER_LINE_NO_PRICE',
  ORDER_PAYMENT_NOT_APPROVED = 'ORDER_PAYMENT_NOT_APPROVED',
  ORDER_PAYMENT_NOT_CAPTURED = 'ORDER_PAYMENT_NOT_CAPTURED',
  PARTIAL_CAPTURE_UNSUPPORTED = 'PARTIAL_CAPTURE_UNSUPPORTED',

  ORDER_IDEMPOTENCY_KEY_REQUIRED = 'ORDER_IDEMPOTENCY_KEY_REQUIRED',
  ORDER_IDEMPOTENCY_KEY_REUSED = 'ORDER_IDEMPOTENCY_KEY_REUSED',
  ORDER_IDEMPOTENCY_KEY_IN_PROGRESS = 'ORDER_IDEMPOTENCY_KEY_IN_PROGRESS',

  ORDER_LINE_VARIANT_INVALID = 'ORDER_LINE_VARIANT_INVALID',
  ORDER_LINE_QUANTITY_INVALID = 'ORDER_LINE_QUANTITY_INVALID',
  ORDER_LINE_SKU_REQUIRED = 'ORDER_LINE_SKU_REQUIRED',
  ORDER_LINE_NAME_REQUIRED = 'ORDER_LINE_NAME_REQUIRED',
  ORDER_LINE_MONEY_INVALID = 'ORDER_LINE_MONEY_INVALID',
  ORDER_LINE_TOTAL_MISMATCH = 'ORDER_LINE_TOTAL_MISMATCH',

  ADDRESS_OWNER_TYPE_INVALID = 'ADDRESS_OWNER_TYPE_INVALID',
  ADDRESS_OWNER_ID_REQUIRED = 'ADDRESS_OWNER_ID_REQUIRED',
  ADDRESS_RECIPIENT_REQUIRED = 'ADDRESS_RECIPIENT_REQUIRED',
  ADDRESS_LINE1_REQUIRED = 'ADDRESS_LINE1_REQUIRED',
  ADDRESS_CITY_REQUIRED = 'ADDRESS_CITY_REQUIRED',
  ADDRESS_REGION_REQUIRED = 'ADDRESS_REGION_REQUIRED',
  ADDRESS_POSTAL_CODE_REQUIRED = 'ADDRESS_POSTAL_CODE_REQUIRED',
  ADDRESS_COUNTRY_INVALID = 'ADDRESS_COUNTRY_INVALID',

  PAYMENT_ORDER_ID_INVALID = 'PAYMENT_ORDER_ID_INVALID',
  PAYMENT_AMOUNT_INVALID = 'PAYMENT_AMOUNT_INVALID',
  PAYMENT_CURRENCY_REQUIRED = 'PAYMENT_CURRENCY_REQUIRED',
  PAYMENT_METHOD_REQUIRED = 'PAYMENT_METHOD_REQUIRED',
  PAYMENT_GATEWAY_REFERENCE_REQUIRED = 'PAYMENT_GATEWAY_REFERENCE_REQUIRED',
  PAYMENT_INVALID_STATUS_TRANSITION = 'PAYMENT_INVALID_STATUS_TRANSITION',

  FULFILLMENT_NOT_FOUND = 'FULFILLMENT_NOT_FOUND',
  FULFILLMENT_NO_LINES = 'FULFILLMENT_NO_LINES',
  FULFILLMENT_LINE_QUANTITY_INVALID = 'FULFILLMENT_LINE_QUANTITY_INVALID',
  FULFILLMENT_QUANTITY_EXCEEDS_REMAINING = 'FULFILLMENT_QUANTITY_EXCEEDS_REMAINING',
  FULFILLMENT_INVALID_STATUS_TRANSITION = 'FULFILLMENT_INVALID_STATUS_TRANSITION',
  FULFILLMENT_TRACKING_REQUIRED = 'FULFILLMENT_TRACKING_REQUIRED',
  ORDER_INVALID_FULFILLMENT_TRANSITION = 'ORDER_INVALID_FULFILLMENT_TRANSITION',

  ORDER_NOT_FULFILLABLE = 'ORDER_NOT_FULFILLABLE',

  ORDER_NOT_CANCELLABLE = 'ORDER_NOT_CANCELLABLE',
  ORDER_LINE_NOT_FOUND = 'ORDER_LINE_NOT_FOUND',

  REFUND_AMOUNT_INVALID = 'REFUND_AMOUNT_INVALID',
  REFUND_REASON_REQUIRED = 'REFUND_REASON_REQUIRED',
  REFUND_INVALID_STATUS_TRANSITION = 'REFUND_INVALID_STATUS_TRANSITION',
  REFUND_EXCEEDS_REFUNDABLE = 'REFUND_EXCEEDS_REFUNDABLE',
  REFUND_PAYMENT_NOT_CAPTURED = 'REFUND_PAYMENT_NOT_CAPTURED',
  REFUND_ACCESS_FORBIDDEN = 'REFUND_ACCESS_FORBIDDEN',
}

export class OrderDomainException extends DomainException {
  public readonly code: OrderErrorCodeEnum;
  public readonly details?: Readonly<Record<string, unknown>>;

  constructor(
    code: OrderErrorCodeEnum,
    message: string,
    details?: Readonly<Record<string, unknown>>,
  ) {
    super(message);
    this.code = code;
    this.details = details;
  }
}
