import { DomainException } from '@retail-inventory-system/common';

export enum CatalogErrorCodeEnum {
  PRODUCT_NAME_REQUIRED = 'CATALOG_PRODUCT_NAME_REQUIRED',
  PRODUCT_SLUG_REQUIRED = 'CATALOG_PRODUCT_SLUG_REQUIRED',
  PRODUCT_INVALID_STATE_TRANSITION = 'CATALOG_PRODUCT_INVALID_STATE_TRANSITION',
  PRODUCT_PUBLISH_REQUIRES_VARIANT = 'CATALOG_PRODUCT_PUBLISH_REQUIRES_VARIANT',
  PRODUCT_PUBLISH_REQUIRES_PRICE = 'CATALOG_PRODUCT_PUBLISH_REQUIRES_PRICE',
  VARIANT_SKU_REQUIRED = 'CATALOG_VARIANT_SKU_REQUIRED',
  VARIANT_OPTION_VALUES_REQUIRED = 'CATALOG_VARIANT_OPTION_VALUES_REQUIRED',
  VARIANT_WEIGHT_INVALID = 'CATALOG_VARIANT_WEIGHT_INVALID',
  VARIANT_DIMENSIONS_INVALID = 'CATALOG_VARIANT_DIMENSIONS_INVALID',
  PRODUCT_NOT_FOUND = 'CATALOG_PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_TAKEN = 'CATALOG_PRODUCT_SLUG_TAKEN',
  VARIANT_SKU_TAKEN = 'CATALOG_VARIANT_SKU_TAKEN',
  VARIANT_NOT_FOUND = 'CATALOG_VARIANT_NOT_FOUND',

  CATEGORY_NAME_REQUIRED = 'CATALOG_CATEGORY_NAME_REQUIRED',
  CATEGORY_SLUG_INVALID = 'CATALOG_CATEGORY_SLUG_INVALID',
  CATEGORY_SORT_ORDER_INVALID = 'CATALOG_CATEGORY_SORT_ORDER_INVALID',
  CATEGORY_INVALID_STATE_TRANSITION = 'CATALOG_CATEGORY_INVALID_STATE_TRANSITION',
  CATEGORY_CYCLE = 'CATALOG_CATEGORY_CYCLE',
  CATEGORY_NOT_FOUND = 'CATALOG_CATEGORY_NOT_FOUND',
  CATEGORY_PARENT_NOT_FOUND = 'CATALOG_CATEGORY_PARENT_NOT_FOUND',
  CATEGORY_SLUG_TAKEN = 'CATALOG_CATEGORY_SLUG_TAKEN',
  CATEGORY_ARCHIVED = 'CATALOG_CATEGORY_ARCHIVED',

  MEDIA_URI_REQUIRED = 'CATALOG_MEDIA_URI_REQUIRED',
  MEDIA_TYPE_INVALID = 'CATALOG_MEDIA_TYPE_INVALID',
  MEDIA_OWNER_TYPE_INVALID = 'CATALOG_MEDIA_OWNER_TYPE_INVALID',
  MEDIA_OWNER_ID_INVALID = 'CATALOG_MEDIA_OWNER_ID_INVALID',
  MEDIA_SORT_ORDER_INVALID = 'CATALOG_MEDIA_SORT_ORDER_INVALID',
  MEDIA_NOT_FOUND = 'CATALOG_MEDIA_NOT_FOUND',
  MEDIA_OWNER_NOT_FOUND = 'CATALOG_MEDIA_OWNER_NOT_FOUND',
  MEDIA_INVALID_STATE_TRANSITION = 'CATALOG_MEDIA_INVALID_STATE_TRANSITION',
  MEDIA_REORDER_SET_MISMATCH = 'CATALOG_MEDIA_REORDER_SET_MISMATCH',
}

export class CatalogDomainException extends DomainException {
  public readonly code: CatalogErrorCodeEnum;

  constructor(code: CatalogErrorCodeEnum, message: string) {
    super(message);
    this.code = code;
  }
}
